### ISSUE TITLE
Any plans to finish this?

### ISSUE THREAD

**Issue by digitalbird01** [bitfocus/companion-module-aver-ptz#7]
What you have is working well but what about Presets? Any plans to add those to the plugin in the near future?

**Comment by Colbix** [comment]
@digitalbird01 Yes, I'm looking at adding more presets and descriptions. I'll look to revisiting the module early next year after the holiday's. I'm glad the module is working well for you.

**Comment by Colbix** [comment]
I created a new branch for testing, see presetupdate. The branch includes more presets, 10 categories worth of presets in fact, a few additional buttons, and logging information. Feel free to check it out. Once I've confirmed no issues with the branch, I'll merge the branch, create a new release, and reach out to the Bitfocus team to have it included in their next build. No timeline on the inclusion at the moment.

**Comment by Colbix** [comment]
@digitalbird01 The preset update has been released.
